// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjpp8ZIeFFcHiek6xDAkVosA_QxTXDdnw',
    appId: '1:147962174148:web:2e0c99a93c57e305528791',
    messagingSenderId: '147962174148',
    projectId: 'project-20251216-a5f62',
    authDomain: 'project-20251216-a5f62.firebaseapp.com',
    storageBucket: 'project-20251216-a5f62.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDME257aHP5TNRq70r3slDR5DYDNrWdklc',
    appId: '1:147962174148:android:ba34e4ed57bf0da7528791',
    messagingSenderId: '147962174148',
    projectId: 'project-20251216-a5f62',
    storageBucket: 'project-20251216-a5f62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBJGegs2i3fUaJUMzmdOXsgjqOmNp7JYI',
    appId: '1:147962174148:ios:cee814cf159f2c73528791',
    messagingSenderId: '147962174148',
    projectId: 'project-20251216-a5f62',
    storageBucket: 'project-20251216-a5f62.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBJGegs2i3fUaJUMzmdOXsgjqOmNp7JYI',
    appId: '1:147962174148:ios:cee814cf159f2c73528791',
    messagingSenderId: '147962174148',
    projectId: 'project-20251216-a5f62',
    storageBucket: 'project-20251216-a5f62.firebasestorage.app',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjpp8ZIeFFcHiek6xDAkVosA_QxTXDdnw',
    appId: '1:147962174148:web:92b91fcd723e5904528791',
    messagingSenderId: '147962174148',
    projectId: 'project-20251216-a5f62',
    authDomain: 'project-20251216-a5f62.firebaseapp.com',
    storageBucket: 'project-20251216-a5f62.firebasestorage.app',
  );
}
